# Generated by Django 4.1.5 on 2023-03-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='user_group_name',
            new_name='name',
        ),
    ]
