# Generated by Django 4.1.7 on 2023-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_group_name_usergroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_login',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
