# Generated by Django 4.1.5 on 2023-01-17 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 16, 15, 50, 512443, tzinfo=datetime.timezone.utc)),
        ),
    ]
