# Generated by Django 4.1.5 on 2023-01-17 17:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.TextField(default=datetime.datetime(2023, 1, 17, 17, 44, 52, 283790, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
