# Generated by Django 4.1.5 on 2023-01-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_title_alter_idea_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='date_posted',
        ),
    ]
