# Generated by Django 4.1.5 on 2023-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_remove_idea_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='type',
            field=models.CharField(choices=[('ICPC', 'ICPC'), ('IOI', 'IOI'), ('-', '-')], default='-', max_length=4),
        ),
    ]
