# Generated by Django 4.1.5 on 2023-01-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_idea_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='idea',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.ideatype'),
        ),
    ]
