# Generated by Django 4.1.5 on 2023-01-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_idea_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.ideatype', verbose_name='idea_type'),
        ),
    ]
