# Generated by Django 4.1.5 on 2023-01-18 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0009_ideatag_alter_idea_type_idea_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='author',
        ),
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(verbose_name='Идея'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tag',
            field=models.ManyToManyField(to='ideas.ideatag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.ideatype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='idea',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
