# Generated by Django 4.1.5 on 2023-01-18 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0010_remove_idea_author_alter_idea_content_alter_idea_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='author',
        ),
        migrations.AddField(
            model_name='idea',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
    ]
