# Generated by Django 4.1.5 on 2023-01-18 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_rename_tag_idea_tags_remove_idea_author_idea_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи'),
        ),
    ]
