# Generated by Django 4.1.5 on 2023-01-21 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0012_idea_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='users_can_edit',
            field=models.ManyToManyField(related_name='idea2person_edit', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которые могут редактировать'),
        ),
        migrations.AddField(
            model_name='idea',
            name='users_can_view',
            field=models.ManyToManyField(related_name='idea2person_view', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которые могут просматривать'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='authors',
            field=models.ManyToManyField(related_name='idea2authors', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='ideas.ideatype', verbose_name='Тип'),
        ),
    ]
