# Generated by Django 4.1.5 on 2023-01-21 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0013_idea_users_can_edit_idea_users_can_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='real_author',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
            preserve_default=False,
        ),
    ]
