# Generated by Django 4.1.5 on 2023-01-21 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0015_rename_date_posted_idea_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
