# Generated by Django 4.1.5 on 2023-01-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0018_alter_idea_date_posted_alter_idea_date_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='ideas.ideastatus', verbose_name='Статус'),
        ),
    ]
