# Generated by Django 4.1.5 on 2023-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0019_ideastatus_idea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideatype',
            name='color',
            field=models.CharField(default='white', max_length=100),
            preserve_default=False,
        ),
    ]
