# Generated by Django 4.1.5 on 2023-01-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0020_ideatype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideatype',
            name='color',
        ),
        migrations.AddField(
            model_name='ideastatus',
            name='color',
            field=models.CharField(default='white', max_length=100),
            preserve_default=False,
        ),
    ]
