# Generated by Django 4.1.5 on 2023-02-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0021_remove_ideatype_color_ideastatus_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='short_editorial',
            field=models.TextField(default='', verbose_name='Идея решения'),
        ),
    ]
