# Generated by Django 4.1.5 on 2023-03-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usergroup'),
        ('ideas', '0023_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-date_update']},
        ),
        migrations.AddField(
            model_name='idea',
            name='groups_access',
            field=models.ManyToManyField(to='users.usergroup', verbose_name='Группы пользователей, которые могут редактировать'),
        ),
    ]
