# Generated by Django 4.1.7 on 2023-03-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0025_alter_comment_date_posted_alter_idea_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
