# Generated by Django 4.1.7 on 2023-04-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0026_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='polygon_task',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Название на полигоне'),
        ),
        migrations.AddField(
            model_name='idea',
            name='difficulty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='ideas.difficulty', verbose_name='Сложность'),
        ),
    ]
