# Generated by Django 4.1.7 on 2023-08-03 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_profile_telegram_login'),
        ('ideas', '0027_difficulty_idea_polygon_task_idea_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups_access', models.ManyToManyField(to='users.usergroup', verbose_name='Группы пользователей, которые могут редактировать')),
            ],
            options={
                'ordering': ['-date_update'],
            },
        ),
        migrations.CreateModel(
            name='IdeaInContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_letter', models.CharField(max_length=10)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='ideas_list',
            field=models.ManyToManyField(through='contests.IdeaInContest', to='ideas.idea', verbose_name='Идеи в контесте'),
        ),
        migrations.AddField(
            model_name='contest',
            name='users_can_edit',
            field=models.ManyToManyField(related_name='contest2person_edit', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которые могут редактировать'),
        ),
        migrations.AddField(
            model_name='contest',
            name='users_can_view',
            field=models.ManyToManyField(related_name='contest2person_view', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которые могут просматривать'),
        ),
    ]
