# Generated by Django 4.1.7 on 2023-08-04 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideaincontest',
            options={'ordering': ['-task_letter']},
        ),
        migrations.AddField(
            model_name='contest',
            name='real_author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор контеста'),
        ),
    ]
