# Generated by Django 4.1.7 on 2023-08-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_ideaincontest_options_contest_real_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideaincontest',
            options={},
        ),
        migrations.RemoveField(
            model_name='ideaincontest',
            name='task_letter',
        ),
    ]
